scrape_configs:
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'num_uploads'
    scrape_interval: 1s
    static_configs:
      - targets: ['app:8000']
